# Generated by Django 4.1.6 on 2023-02-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_planning',
            name='status',
            field=models.CharField(choices=[(1, 'on_side'), (2, 'remote')], default='on_side', max_length=10),
        ),
        migrations.AlterField(
            model_name='work_planning',
            name='name',
            field=models.CharField(max_length=50, verbose_name='işçilərin siyahısı'),
        ),
    ]
