# Generated by Django 4.1.6 on 2023-02-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_work_planning_status_alter_work_planning_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_planning',
            name='status',
            field=models.CharField(choices=[(1, 'on_side'), (2, 'remote')], default=1, max_length=10),
        ),
    ]
