# Generated by Django 4.1.6 on 2023-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_work_planning_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_planning',
            name='status',
            field=models.IntegerField(choices=[(1, 'on_side'), (2, 'remote')], default=1, max_length=10),
        ),
    ]
