# Generated by Django 4.1.6 on 2023-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_work_planning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_planning',
            name='name_id',
        ),
        migrations.AddField(
            model_name='work_planning',
            name='name',
            field=models.ManyToManyField(to='Core.employees'),
        ),
    ]
