# Generated by Django 4.1.6 on 2023-02-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_work_planning_department_employees_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_planning',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Departament'),
        ),
    ]
