# Generated by Django 4.1.6 on 2023-02-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_work_planning_department_alter_employees_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department',
        ),
    ]
