# Generated by Django 4.1.6 on 2023-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='işçilərin siyahısı'),
        ),
    ]
