# Generated by Django 4.1.6 on 2023-02-28 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0013_department_remove_work_planning_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_planning',
            new_name='WorkPlanning',
        ),
    ]
