# Generated by Django 4.1.6 on 2023-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_thetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thetable',
            name='number',
        ),
        migrations.AddField(
            model_name='thetable',
            name='ranking',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
