# Generated by Django 4.1.6 on 2023-03-01 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0016_remove_thetable_number_thetable_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.RemoveField(
            model_name='workplanning',
            name='author',
        ),
        migrations.AlterField(
            model_name='workplanning',
            name='employees_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
