# Generated by Django 4.1.6 on 2023-03-01 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0018_employees_workplanning_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplanning',
            name='author',
        ),
        migrations.RemoveField(
            model_name='workplanning',
            name='employees_id',
        ),
        migrations.AddField(
            model_name='workplanning',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
