# Generated by Django 4.1.6 on 2023-03-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_remove_workplanning_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
