# Generated by Django 4.1.6 on 2023-03-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_delete_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplanning',
            name='department_id',
        ),
        migrations.AddField(
            model_name='department',
            name='work_planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Core.workplanning'),
        ),
    ]
