# Generated by Django 4.1.6 on 2023-03-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_remove_workplanning_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='workplanning',
            old_name='employees',
            new_name='employees_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='work_planning',
        ),
        migrations.AddField(
            model_name='workplanning',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.department'),
        ),
    ]
