# Generated by Django 4.1.6 on 2023-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_employees_rename_employees_workplanning_employees_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.RenameField(
            model_name='workplanning',
            old_name='department',
            new_name='department_id',
        ),
    ]
