# Generated by Django 4.1.6 on 2023-03-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_delete_employees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPlanning',
        ),
    ]
