# Generated by Django 4.1.6 on 2023-03-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_delete_workplanning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thetable',
            old_name='ranking',
            new_name='name',
        ),
    ]
