# Generated by Django 4.1.6 on 2023-03-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_remove_department_table_thetable_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thetable',
            name='table',
        ),
    ]
