# Generated by Django 4.1.6 on 2023-03-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_remove_thetable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='Core.thetable'),
        ),
    ]
