# Generated by Django 4.1.4 on 2023-03-03 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0032_alter_thetable_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetable',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to=settings.AUTH_USER_MODEL),
        ),
    ]
